### ISSUE TITLE
Feature request: Execute async JS

### ISSUE THREAD

**Issue by vchaban** [testerum/testerum#13]
Hello,

First of all, I wanna thank you for a great job, this project is awesome.

We are trying to evaluate Testerum and we have faced an issue, in the current world of SPA websites, we need to track some async things like AJAX request. With the existing step to execute JS in the browser, it seems would be very tricky. From what I can see Selenium supports running async JS and this would be awesome if Testerum can provide such a step too.

Best Regards

**Comment by ionut-pruteanu** [comment]
Hello,

I am very happy that you like our product an thank you for pointing out something that we are missing.
We made a release last evening to fix your request.

Now, we have added this step:
![image](https://user-images.githubusercontent.com/2930047/97152084-b2e41480-1770-11eb-9336-8f0c5f9725d8.png)

In can you find more of missing steps and you want to have a quick fix until we do the proper fix you can do something like in the next example:

![image](https://user-images.githubusercontent.com/2930047/97152439-2f76f300-1771-11eb-8458-ad0f9193a9ac.png)

Using the step "When execute the WebDriver JS script" you have access to the webDriver instance and you can call any methods that we have missed. 

But in case you find such a scenario please let us know too.

In case you have more questions or challenging scenarios please contact us at contact@testerum.com and we can setup a call. We are interested in your needs to make sure we are creating a great  product.

Best Regards

**Comment by vchaban** [comment]
OMG, this was fast. :+1: 

Thank you so much, I will give a try.

Having direct access to the webDriver is very useful information. 
If I will find something missing I will let you know, I would glad to help improve this project.

Keep going guys.

For now, I'm going to close this issue.

Best Regards
