### ISSUE TITLE
Feature Request: Add a Google Auth Step 

### ISSUE THREAD

**Issue by medavian** [testerum/testerum#14]
Hey Team,

As part of most sites these days, I need to be able to simulate a login via 2FA. In this case, the 2FA uses a Google Auth style token.

Is it possible to add a step where we provide a secret as a parameter to a step and it returns the current token value in a variable? This could then be used in the following step(s) to complete a 2FA login. 

Appreciate if you could look into this as I feel this would be a good addition to the step library.

If you need anything further, please let me and I will assist where I can.

Kind Regards,
Darrin

**Comment by ionut-pruteanu** [comment]
Hi Darrin,

To implement this there are 2 options:
 1. Create a Custom Step and implement the functionality in Java.
 2. Create a small script that can be executed in the browser.

For the step 2. I just will add an implementation example:
![image](https://user-images.githubusercontent.com/2930047/98871464-3c842980-2475-11eb-93e2-5049b01114b8.png)
