### ISSUE TITLE
Bug: Running the tests from the Reports page gives no visual indication

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#19]
Reproduction steps:
* Open a project
* Set up a Run configuration
* Visit the reports page
* Press the green Play button in the top bar

Notice how there is no visual indication whatsoever that a test run has been kicked off. The UI is also not updated at the end of the test run, and the page needs to be refreshed to see the latest test results.

**Comment by ionut-pruteanu** [comment]
Thank you for reporting this issue. This is for sure a usability problem. We need to think what is a good solution!

**Comment by ionut-pruteanu** [comment]
This issue has been fixed. Will be available in the next release, 4.1.0.

If you run a configuration from a different page then the project page, you will be moved to the project page and then the Run config will be run.
