### ISSUE TITLE
Bug: Can't edit sub step in the custom step if it is added twice to the test.

### ISSUE THREAD

**Issue by vchaban** [testerum/testerum#21]
Hi team,

I faced a problem with updating the custom step. 

You need to have a test with a custom step and sub-step in it.
Add this custom step one more time in the same test as a sub-step of another test.
Any changes to the custom step sub-step will not be saved on test save.

Yay, I don't know how to write bug reports (, sorry,
so, here the screenshot of the sample test ;)
![image](https://user-images.githubusercontent.com/52444838/98848497-7ac01f80-245a-11eb-9473-ec24e6138c13.png)

When I trying to change the script of the '**When** I execute the WebDriver JS script <<console.log('Hello world 112');>> in the browser'  and save the test, my changes not saved.

Thanks

Best Regards
Vadym

**Comment by imariusgradinaru** [comment]
Hi Vadym,

I'm Marius and I'm part of Testerum team.
Thank you for using Testerum and sharing your feedback with us.

I tried myself the same test case as you have in here, and I noticed the following:

- if you create a test and a custom step that is used in the next steps (as you have here), and you want to modify the sub-step of the custom step, everything will be updated after you press the Save button.

I hope my answer was helpful to you.
Please let us know.

Regards,
Marius

**Comment by vchaban** [comment]
Hi Marius,

Thank you, that's weird, ok, I will test on more time.

Best Regards
Vadym

**Comment by imariusgradinaru** [comment]
Hi Vadim,

You're welcome. Please let us know and we are happy to have a short private call to help you on Skype, Teams, etc.

Regards,
Marius
