### ISSUE TITLE
Bug: nested composed steps lose composed step arguments

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#29]
Given:
* Composed step 1 has two arguments
* Composed step 2 has no arguments
* Composed step 1 calls out to composed step 2

Once composed step 2 is executed by the runner, the first composed step's arguments won't be available for any subsequent steps defined in composed step 1.
I've attached an example project that demonstrates the issue.
Note how the first log all variables step logs the two arguments, but the last step no longer lists the original arguments.
[hello.zip](https://github.com/testerum/testerum/files/5638341/hello.zip)

**Comment by cvmocanu** [comment]
Thanks a lot for reporting this (in such a nicely reproducible way too).
We'll fix this very soon.

**Comment by cvmocanu** [comment]
Fixed in version 5.0.2
