### ISSUE TITLE
Bug: Test tag selection does not appear to work on Run Configurations

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#33]
Reproduction steps:
* create two tests, add "test" tag to only one of them
* In the Run configurations dropdown on the top of the page (in the middle next to the play button), select Edit Configurations...
* Add a new Run Configuration and make sure that Tags to include contains "test"
* Save
* Select the new run configuration in the dropdown and press play

Notice how all the tests are being executed regardless of their tags.

**Comment by ionut-pruteanu** [comment]
This issue has been fixed. Will be available in the next release, 4.1.0.
