### ISSUE TITLE
Bug: Resource folder cannot be renamed

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#34]
Steps to reproduce:
* Create a new HTTP Request resource folder called "Old"
* Create a new HTTP Request under the folder (without this step the folder disappears on page refresh)
* Click on the pencil icon next to the resource folder
* Enter a new folder name
* Press Save
* The UI shows the new folder name, but if you refresh the page, the folder still has its old name.

**Comment by ionut-pruteanu** [comment]
This issue has been fixed. Will be available in the next release, 4.1.0.
