### ISSUE TITLE
Bug: After hook failure marks test as failure

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#48]
Steps to reproduce:

Create a new test
Add a test step that will not cause failure
Add an after hook that will fail (ex: "When I log all the variables")
Run test
Note: notice how the test is marked as failed

Details:

Linux
v5.0.2

**Comment by ionut-pruteanu** [comment]
Hi Ajhad,

We consider that a hook is part of the test. 
This behavior is as designed. If a hook fails, the test fails.
We made a test and JUnit has the same behavior.

Do you have a good reason where you would like to have a different behavior?

**Comment by aldaris** [comment]
Hi Ionut,

Consistency with other test frameworks makes perfect sense, however it appears that the help texts in the product are incorrect then. For example the After Each test has this:

![Screenshot 2021-01-26 at 15 03 14](https://user-images.githubusercontent.com/206692/105865517-ebeb8980-5fea-11eb-82ad-f1d83b13647b.png)

The After All Tests hook's info text is also wrong I believe. The last test won't be marked as failed, but the test suite will be. (Also there are potentially two typos in there: Functionality -> Feature and previews -> previous).

**Comment by ionut-pruteanu** [comment]
Thank you for this reporting this. Very hard to spot this details.
I changed the documentation. Will be available in the next release.
