### ISSUE TITLE
Bug Report: composed steps and resources in hooks are not updated when they are changed

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#50]
Steps to reproduce:

Go to the "Steps" page
Create a new composed step with the name "Given I test"
Go to the "Project" page
Create a new feature
Add the composed step to the hook
Go to the "Steps" page
Edit the name of the composed step to be "Given I test123"
Go to the "Project" page
View the hooks for the feature
Note: no changes to the name or steps will be shown

Details:

Linux
v5.0.2

-----Update-----
Copying and pasting a feature with hooks seems to force the update of the hooks of all features

**Comment by ionut-pruteanu** [comment]
Thank you for reporting this issue, is a big one. 
Is fixed now, will be available in the next release.

**Comment by aldaris** [comment]
Thanks, it works as expected in version 5.0.5. Feel free to close out this issue.
