### ISSUE TITLE
Bug: When executing a manual test plan the Next button is displayed on last test in the plan

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#57]
Steps to reproduce:
* Set up a manual test with a couple of dummy test steps
* Go to Manual tab, and set up a new Test plan that includes only that new manual test
* Execute the new plan
* Notice how the bottom button bar has a Next button (that does absolutely nothing), even when you are on the last test in the plan.

**Comment by ionut-pruteanu** [comment]
Thank you again for reporting your findings.
Is fixed, will be available in the next release.
