### ISSUE TITLE
Bug: Test comment is not displayed when viewing already finished test plans

### ISSUE THREAD

**Issue by aldaris** [testerum/testerum#58]
Steps to reproduce:

* Set up a manual test with more than one dummy test steps
* Go to Manual tab, and set up a new Test plan that includes only that new manual test
* Execute the new plan
* Mark the first test step as Failed in the right column
* Type in some message into the Comment field
* Save page
* Navigate away to a different tab, like Reports
* Go back to Manual
* Select Execute on the previously created test plan (should it be a View button instead?)
* Look how the Comment field is displayed as completely empty
* Double click on the greyed out input field - the comment magically shows up

**Comment by ionut-pruteanu** [comment]
Fixed
