### ISSUE TITLE
Feature Request: Add ability to run step even if previous step failed

### ISSUE THREAD

**Issue by Ajhad1** [testerum/testerum#8]
In response to https://github.com/testerum/testerum/issues/6#issuecomment-700356303
> Currently hooks are planned, but not yet implemented.
> As a (hacky) workaround, you can group the steps you want as part of a hook in a composed step, and manually add this composed step before/after each test.

Would it be possible to add a button next to the disable button on the test screen that would allow a step to be marked to run even if the previous step has failed?
As hooks are currently plan, and the workaround suggested does not work for steps at the end of a failed test, I believe a temporary stopgap fix would be to add the button mentioned above and adjust the logic of when to run a step to check for the same type of meta data used to not run a step when disabled.

I am including a photo of where the button would be in my mind. 
![image](https://user-images.githubusercontent.com/24377175/95139563-c3d5d300-073a-11eb-9eb6-e9d08ac5885b.png)

If I need to provide any more information, let me know.

**Comment by cvmocanu** [comment]
Hi @Ajhad1,

Thanks for the suggestion.

Currently, hooks are supported by writing Java (or any other JVM language) code, using the annotations ``@BeforeAllTests``, ``@BeforeEachTest``, ``@AfterEachTest``, ``@AfterAllTests``.

See an example here: https://github.com/testerum/testerum/blob/6678788bb0389560bd3b2439a063e2332fcd7b28/testerum-backend/testerum-scanner-it/testerum-scanner-it-steplib1/src/main/kotlin/com/testerum/scanner_it_steplib1/steps/StepLib1MySteps.kt#L100-L136
We are currently documenting how to write basic steps using Java, and this will include these kinds of hooks.

In addition, we want to implement, in the very immediate future, hooks that you can create in the UI.
This will be a better alternative to having a flag per step. Such a flag:
* would be less flexible
* would complicate the runner code
* would complicate the UI to make sure we automatically move such steps at the end

For this reason, I will close this ticket.
Hooks in the UI are coming very soon :)
